# Generated by Django 3.1.13 on 2021-08-16 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_blog', '0039_auto_20200331_2227'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='discussions_discussionpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('rendering_template', models.CharField(choices=[('discussions/plugins/discussion_template1.html', 'Template 1')], default='discussions/plugins/discussion_template1.html', help_text='Select plugin template to load for this instance', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('subject', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='approved')),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('date_approved', models.DateTimeField(blank=True, null=True, verbose_name='published since')),
                ('end_discussion_date', models.DateTimeField(blank=True, null=True, verbose_name='published until')),
                ('sort', models.PositiveSmallIntegerField(default=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='djangocms_blog.blogcategory')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discussions', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'ordering': ['sort', 'date_created'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('body', models.TextField(blank=True, null=True)),
                ('discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='discussions.discussion')),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='poster')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
